# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ze9zbEL4dAjlcT0gZWIegpplI-1M1E88

#Tema 1: Imprimir 'Hola Mundo'
"""

#Impresion de caracteres tipo string, 'Hola Mundo'
print('Hola',' ','mundo')

nombre = 'Adhara'
carrera = 'DCC'

print(f"{nombre} es de la carrera de {carrera}")
print(f'{nombre} es de la carrera de {carrera}')

"""Actividad 1. Imprimir nombre, apellido y carrera al que pertenecen.

"""

#Impresion de datos del usuario usando formato f" {variable} "
nombre = "Angel"
apellido = "Barron"
carrera = "ISC"
print(f"Nombre: {nombre}, Apellido: {apellido}, Carrera: {carrera}")

# Uso de concatenación para mostrar variables en pantalla
nombre = "Jose"
edad = 30
carrera = 'Ciencias de Datos'
semestre = '2do'
print('Hola', nombre, 'de', carrera,'es un viejo de',edad,'años, y va en', semestre, 'semestre')
print('Hola ' + nombre + ' de ' + carrera + ' es un viejo de ' + str(edad) + ' años, y va en ' + str(semestre) + ' semestre')

#Pedir datos al usuario para su correspondiente impresion en consola
nombre = input('¿Como te llamas?')
edad = int(input("¿Que edad tienes?"))
estatura = float(input('¿Cuanto mides?'))
print(f'Hola {nombre} de {edad} anios y mide {estatura}')

#Script de operadores aritmeticos
print(25*(3+2-4)/5)
x = 9
y = 15
print(f"La suma de los numeros es: {x+y}")
print(f"La resta es: {x-y}")
print(f"La multiplicacion de los numeros es: {x*y}")
print(f"La division de los numeros es: {x//y}")
print(x*y+y/x**x+y)

# Script interactivo para realizar operaciones matemáticas básicas
x = int(input("Primer valor: "))
y = int(input("Segundo valor: "))

print(f"¿Que operacion desea: ")
print(f"1) suma")
print(f"2) Resta")
print(f"3) Multiplicacion")
print(f"4) Division")

operacion = int(input())

if operacion == 1:
  print(f"La respuesta es: {x+y}")
elif operacion == 2:
  print(f"La respuesta es: {x-y}")
elif operacion == 3:
  print(f"La respuesta es: {x*y}")
else:
  print(f"La respuesta es: {x//y}")

"""if/for/while

"""

#Introduccion al for en python
for i in range(10):
  print(i)

# Imprime una secuencia de números del 1 al 10 con paso de 3

for i in range(1,11,3):
  print(i)

# Imprime los valores del 0 al 5 usando un bucle while
cont = 0
while cont <= 5:
  print(f"El valor es: {cont}")
  cont += 1

# Cálculo del promedio de calificaciones usando dos métodos distintos
calif = [4, 6, 9, 7, 5]
suma = 0
for i in range(len(calif)):
  #print(f"Posicion  {i} Calificacion: {calif[i]}")
  suma = suma + calif[i]
print(suma)
prom = suma / len(calif)
#print(prom)

op = 0
for e in calif:
  op += e

print(f"Promedio: {op/len(calif)}")

# Captura una cantidad definida de valores enteros y los almacena en una lista
cantidad = int(input("Cantidad de datos: "))
lista = []
for i in range(cantidad):
  lista.append(int(input("Value: ")))
print(lista)

"""Actividad 2. Dada una secuencia de 15 numeros, imprimir cantidad de numeros
impares en pares, e imprimir la lista completa
"""

# Cuenta cuántos valores impares hay en posiciones pares dentro de una lista
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
c = sum(1 for i in range(0, len(nums), 2) if nums[i] % 2)
print(c)
print(nums)

"""Archivos"""

# Introducción a los archivos en Python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_excel('/content/sample_data/datos.xlsx')
df.head()

# Estadísticos del Parcial 1
print("Promedio P1:", df['Parcial 1'].mean())
print("Mínimo P1:", df['Parcial 1'].min())
print("Máximo P1:", df['Parcial 1'].max())

# Calcular promedio de parciales
df['prom'] = df[['Parcial 1', 'Parcial 2', 'Parcial 3']].mean(axis=1)

# Determinar estatus
df['estatus'] = np.where(df['prom'] >= 7, 'Aprobado', 'Reprobado')

# Guardar en Excel
df.to_excel('datos_mod.xlsx', index=False)

print("\nArchivo 'datos_mod.xlsx' generado correctamente.")

# Visualiza la variación de temperatura a lo largo del tiempo usando matplotlib
import matplotlib.pyplot as plt

tiempo = [1,4,6,8,10,12]
temperatura = [20,23,27,25,23,19]
plt.plot(tiempo, temperatura)
plt.xlabel('Tiempo (hrs)')
plt.ylabel('Temperatura (ºC)')
plt.grid(True)
plt.show()

# Visualiza promedios por materia y distribución de calificaciones con matplotlib
import numpy as np
import matplotlib.pyplot as plt

# Datos para la gráfica de barras
materias = ['Programacion', 'Fisica', 'Geometria', 'Calculo']
promedios = [66, 55, 78, 92]

plt.bar(materias, promedios)
plt.ylabel('Promedio')
plt.show()

# Datos del histograma
calificaciones = np.array([60, 70, 45, 67, 89, 34, 4, 56, 65, 98])

plt.hist(calificaciones, bins=5)
plt.xlabel('Calificaciones')
plt.ylabel('Frecuencia')
plt.show()

# Análisis estadístico básico de temperaturas usando NumPy
import numpy as np
temps = np.array([20,23,27,25,23,19])
print('Temperaturas: ', temps)
print('Promedio: ', temps.mean())
print('Mediana: ', temps.min())
print('Max: ', temps.max())

# Cálculo de potencia eléctrica (P = V * I) multiplicando voltaje por corriente elemento a elemento
voltajes = np.array([5,5,5,5])
corrientes = np.array([1,2,3,4])
potencias = voltajes*corrientes
print('Potencias: ',potencias)

# Extracción y visualización de la evolución de notas para el alumno con ID 5
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('/content/sample_data/datos.csv', sep=';')
alumno = 5
notas=df[df['ID']==alumno][['Parcial 1', 'Parcial 2', 'Parcial 3']].iloc[0]

plt.plot(['Parcial 1', 'Parcial 2', 'Parcial 3'], notas)
plt.ylim(0, 10)
plt.ylabel(f'Notas del alumno {alumno}')
plt.title('Evaluaciones de alumnos')
plt.show()